// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/guess': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/guess.post').default>>>>
    }
    '/api/screenshots/random': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/screenshots/random.get').default>>>>
    }
    '/api/upload': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/upload.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
  }
}
export {}