// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 4/21/2025, 9:13:29 AM
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/vanceandersen/Desktop/Projects/HaloGuessr/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/vanceandersen/Desktop/Projects/HaloGuessr/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/vanceandersen/Desktop/Projects/HaloGuessr/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/vanceandersen/Desktop/Projects/HaloGuessr/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/vanceandersen/Desktop/Projects/HaloGuessr/plugins/**/*.{js,ts,mjs}","/Users/vanceandersen/Desktop/Projects/HaloGuessr/composables/**/*.{js,ts,mjs}","/Users/vanceandersen/Desktop/Projects/HaloGuessr/utils/**/*.{js,ts,mjs}","/Users/vanceandersen/Desktop/Projects/HaloGuessr/pages/index.vue","/Users/vanceandersen/Desktop/Projects/HaloGuessr/pages/upload.vue","/Users/vanceandersen/Desktop/Projects/HaloGuessr/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/vanceandersen/Desktop/Projects/HaloGuessr/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/vanceandersen/Desktop/Projects/HaloGuessr/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;